/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/env.d.ts` (hash: cdb34ec5f80087cbf82052b80e8df835)
interface __BaseEnv_Env {
	GOLD_CACHE: DurableObjectNamespace<import("./index").GoldCache>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GoldCache";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
